
version: '3.8'
services:
  
  app:
    container_name: chat_app
    build:
      context: .
    env_file:
      - .env
      
    volumes:
      - .:/app
      - /app/node_modules

    ports:
      - '9000:9000'
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres-db
    image: postgres:12
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    
volumes:
  pgdata: